version: '2'
services:
  chromedriver-docker-example:
    build: .
    image: hronom/chromedriver-docker-example
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8117:8117"
    logging:
      driver: json-file
      options:
        max-size: "250m"
        max-file: "10"